[project]
name = "odoo-addons-sygel-technology-sy-account-invoice-reporting"
version = "17.0.20250527.0"
dependencies = [
    "odoo-addon-account_invoice_report_shipping_ref>=17.0dev,<17.1dev",
    "odoo-addon-delete_payment_reference_invoice_report>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
